# Generated by Django 3.2.14 on 2022-07-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField()),
                ('task_id', models.IntegerField()),
                ('Assignee', models.CharField(max_length=500)),
                ('task_title', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=15)),
                ('priority', models.CharField(max_length=2)),
                ('deadline', models.CharField(max_length=15)),
            ],
        ),
    ]
